name: "Bug Report"
description: Describe the bug 
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Describe the bug or unusual menu behavior. If the problem is "strange" or "hidden", be sure to look at the log. 

  - type: checkboxes
    validations:
      required: true  
    attributes:
      label: Checks
      options:
        - label: >
            I tried to fix the problem myself by reading the contents of the Errors.log
      
  - type: textarea
    attributes:
      label: Description without log
      description: A clear and concise description of what the problem is
    validations:
      required: true
  
  - type: textarea
    validations:
      required: true
    attributes:
      label: Errors log
      description: Attach Errors.log file from script directory    
      value: >
        ```js
        
        Replace this line with the log contents.

        ```
        
  - type: textarea
    attributes:
      label: Images
      description: Attach screenshots with an error in MsgBox. If necessary, attach screenshots not directly related to the error. Or attach gif with unusual behavior. 
    validations:
      required: false
